name: ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ libopenblas-dev

      - name: Compile OpenBLAS double test
        run: g++ -O2 -fopenmp test_gemm_openblas_double.cpp -o test_gemm_openblas_double -lopenblas -lpthread

      - name: Compile OpenBLAS float test
        run: g++ -O2 -fopenmp test_gemm_openblas_float.cpp -o test_gemm_openblas_float -lopenblas -lpthread

      - name: Compile my_gemm double
        run: g++ -O2 -pthread my_gemm_double.cpp -o my_gemm_double

      - name: Compile my_gemm float
        run: g++ -O2 -pthread my_gemm_float.cpp -o my_gemm_float