name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ libopenblas-dev

    - name: Compile my GEMM (float)
      run: g++ -O3 -march=native -pthread my_gemm_float.cpp -o my_gemm_float

    - name: Compile my GEMM (double)
      run: g++ -O3 -march=native -pthread my_gemm_double.cpp -o my_gemm_double

    - name: Run my GEMM float
      run: ./my_gemm_float

    - name: Run my GEMM double
      run: ./my_gemm_double

    - name: Compile OpenBLAS test (float)
      run: g++ -O3 -march=native -fopenmp test_gemm_openblas_float.cpp -o test_gemm_openblas_float -lopenblas -lpthread

    - name: Compile OpenBLAS test (double)
      run: g++ -O3 -march=native -fopenmp test_gemm_openblas_double.cpp -o test_gemm_openblas_double -lopenblas -lpthread

    - name: Run OpenBLAS float
      run: ./test_gemm_openblas_float

    - name: Run OpenBLAS double
      run: ./test_gemm_openblas_double
